<?php

return [
    ['city_id' => '1', 'city_name' => 'Karachi', 'city_state' => 'Sindh'],
    ['city_id' => '2', 'city_name' => 'Lahore', 'city_state' => 'Punjab'],
    ['city_id' => '3', 'city_name' => 'Faisalabad', 'city_state' => 'Punjab'],
    ['city_id' => '4', 'city_name' => 'Rawalpindi', 'city_state' => 'Punjab'],
    ['city_id' => '5', 'city_name' => 'Gujranwala', 'city_state' => 'Punjab'],
    ['city_id' => '6', 'city_name' => 'Peshawar', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '7', 'city_name' => 'Multan', 'city_state' => 'Punjab'],
    ['city_id' => '8', 'city_name' => 'Hyderabad', 'city_state' => 'Sindh'],
    ['city_id' => '9', 'city_name' => 'Islamabad', 'city_state' => 'Islamabad Capital Territory'],
    ['city_id' => '10', 'city_name' => 'Quetta', 'city_state' => 'Balochistan'],
    ['city_id' => '11', 'city_name' => 'Bahawalpur', 'city_state' => 'Punjab'],
    ['city_id' => '12', 'city_name' => 'Sargodha', 'city_state' => 'Punjab'],
    ['city_id' => '13', 'city_name' => 'Sialkot', 'city_state' => 'Punjab'],
    ['city_id' => '14', 'city_name' => 'Sukkur', 'city_state' => 'Sindh'],
    ['city_id' => '15', 'city_name' => 'Larkana', 'city_state' => 'Sindh'],
    ['city_id' => '16', 'city_name' => 'Rahim Yar Khan', 'city_state' => 'Punjab'],
    ['city_id' => '17', 'city_name' => 'Sheikhupura', 'city_state' => 'Punjab'],
    ['city_id' => '18', 'city_name' => 'Jhang', 'city_state' => 'Punjab'],
    ['city_id' => '19', 'city_name' => 'Dera Ghazi Khan', 'city_state' => 'Punjab'],
    ['city_id' => '20', 'city_name' => 'Gujrat', 'city_state' => 'Punjab'],
    ['city_id' => '21', 'city_name' => 'Sahiwal', 'city_state' => 'Punjab'],
    ['city_id' => '22', 'city_name' => 'Wah Cantonment', 'city_state' => 'Punjab'],
    ['city_id' => '23', 'city_name' => 'Mardan', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '24', 'city_name' => 'Kasur', 'city_state' => 'Punjab'],
    ['city_id' => '25', 'city_name' => 'Okara', 'city_state' => 'Punjab'],
    ['city_id' => '26', 'city_name' => 'Mingora', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '27', 'city_name' => 'Nawabshah', 'city_state' => 'Sindh'],
    ['city_id' => '28', 'city_name' => 'Chiniot', 'city_state' => 'Punjab'],
    ['city_id' => '29', 'city_name' => 'Kotri', 'city_state' => 'Sindh'],
    ['city_id' => '30', 'city_name' => 'Kāmoke', 'city_state' => 'Punjab'],
    ['city_id' => '31', 'city_name' => 'Hafizabad', 'city_state' => 'Punjab'],
    ['city_id' => '32', 'city_name' => 'Sadiqabad', 'city_state' => 'Punjab'],
    ['city_id' => '33', 'city_name' => 'Mirpur Khas', 'city_state' => 'Sindh'],
    ['city_id' => '34', 'city_name' => 'Burewala', 'city_state' => 'Punjab'],
    ['city_id' => '35', 'city_name' => 'Kohat', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '36', 'city_name' => 'Khanewal', 'city_state' => 'Punjab'],
    ['city_id' => '37', 'city_name' => 'Dera Ismail Khan', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '38', 'city_name' => 'Turbat', 'city_state' => 'Balochistan'],
    ['city_id' => '39', 'city_name' => 'Muzaffargarh', 'city_state' => 'Punjab'],
    ['city_id' => '40', 'city_name' => 'Abbottabad', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '41', 'city_name' => 'Hanumangarh', 'city_state' => 'Punjab'],
    ['city_id' => '42', 'city_name' => 'Jacobabad', 'city_state' => 'Sindh'],
    ['city_id' => '43', 'city_name' => 'Shikarpur', 'city_state' => 'Sindh'],
    ['city_id' => '44', 'city_name' => 'Muridke', 'city_state' => 'Punjab'],
    ['city_id' => '45', 'city_name' => 'Jhelum', 'city_state' => 'Punjab'],
    ['city_id' => '46', 'city_name' => 'Kamalia', 'city_state' => 'Punjab'],
    ['city_id' => '47', 'city_name' => 'Matiari', 'city_state' => 'Sindh'],
    ['city_id' => '48', 'city_name' => 'Khuzdar', 'city_state' => 'Balochistan'],
    ['city_id' => '49', 'city_name' => 'Pakpattan', 'city_state' => 'Punjab'],
    ['city_id' => '50', 'city_name' => 'Hub', 'city_state' => 'Balochistan'],
    ['city_id' => '51', 'city_name' => 'Dadu', 'city_state' => 'Sindh'],
    ['city_id' => '52', 'city_name' => 'Gojra', 'city_state' => 'Punjab'],
    ['city_id' => '53', 'city_name' => 'Mandi Bahauddin', 'city_state' => 'Punjab'],
    ['city_id' => '54', 'city_name' => 'Tando Allahyar', 'city_state' => 'Sindh'],
    ['city_id' => '55', 'city_name' => 'Bahawalnagar', 'city_state' => 'Punjab'],
    ['city_id' => '56', 'city_name' => 'Samundri', 'city_state' => 'Punjab'],
    ['city_id' => '57', 'city_name' => 'Jaranwala', 'city_state' => 'Punjab'],
    ['city_id' => '58', 'city_name' => 'Chishtian', 'city_state' => 'Punjab'],
    ['city_id' => '59', 'city_name' => 'Attock', 'city_state' => 'Punjab'],
    ['city_id' => '60', 'city_name' => 'Vihari', 'city_state' => 'Punjab'],
    ['city_id' => '61', 'city_name' => 'Khanpur', 'city_state' => 'Punjab'],
    ['city_id' => '62', 'city_name' => 'Leiah', 'city_state' => 'Punjab'],
    ['city_id' => '63', 'city_name' => 'Kandhkot', 'city_state' => 'Sindh'],
    ['city_id' => '64', 'city_name' => 'Tando Adam', 'city_state' => 'Sindh'],
    ['city_id' => '65', 'city_name' => 'Nowshera', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '66', 'city_name' => 'Charsadda', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '67', 'city_name' => 'Karak', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '68', 'city_name' => 'Mianwali', 'city_state' => 'Punjab'],
    ['city_id' => '69', 'city_name' => 'Mirpur', 'city_state' => 'Azad Kashmir'],
    ['city_id' => '70', 'city_name' => 'Chiniot', 'city_state' => 'Punjab'],
    ['city_id' => '71', 'city_name' => 'Kamoke', 'city_state' => 'Punjab'],
    ['city_id' => '72', 'city_name' => 'Hafizabad', 'city_state' => 'Punjab'],
    ['city_id' => '73', 'city_name' => 'Kohāt', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '74', 'city_name' => 'Kharian', 'city_state' => 'Punjab'],
    ['city_id' => '75', 'city_name' => 'Muzaffarabad', 'city_state' => 'Azad Kashmir'],
    ['city_id' => '76', 'city_name' => 'Jalalpur Jattan', 'city_state' => 'Punjab'],
    ['city_id' => '77', 'city_name' => 'Gwadar', 'city_state' => 'Balochistan'],
    ['city_id' => '78', 'city_name' => 'Mansehra', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '79', 'city_name' => 'Mian Channu', 'city_state' => 'Punjab'],
    ['city_id' => '80', 'city_name' => 'Bhakkar', 'city_state' => 'Punjab'],
    ['city_id' => '81', 'city_name' => 'Zhob', 'city_state' => 'Balochistan'],
    ['city_id' => '82', 'city_name' => 'Dipalpur', 'city_state' => 'Punjab'],
    ['city_id' => '83', 'city_name' => 'Khairpur', 'city_state' => 'Sindh'],
    ['city_id' => '84', 'city_name' => 'Kundian', 'city_state' => 'Punjab'],
    ['city_id' => '85', 'city_name' => 'Umarkot', 'city_state' => 'Sindh'],
    ['city_id' => '86', 'city_name' => 'Ahmedpur East', 'city_state' => 'Punjab'],
    ['city_id' => '87', 'city_name' => 'Kot Addu', 'city_state' => 'Punjab'],
    ['city_id' => '88', 'city_name' => 'Wazirabad', 'city_state' => 'Punjab'],
    ['city_id' => '89', 'city_name' => 'Layyah', 'city_state' => 'Punjab'],
    ['city_id' => '90', 'city_name' => 'Chaman', 'city_state' => 'Balochistan'],
    ['city_id' => '91', 'city_name' => 'Taxila', 'city_state' => 'Punjab'],
    ['city_id' => '92', 'city_name' => 'Narowal', 'city_state' => 'Punjab'],
    ['city_id' => '93', 'city_name' => 'Shahdadpur', 'city_state' => 'Sindh'],
    ['city_id' => '94', 'city_name' => 'Kabal', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '95', 'city_name' => 'Hasilpur', 'city_state' => 'Punjab'],
    ['city_id' => '96', 'city_name' => 'Chichawatni', 'city_state' => 'Punjab'],
    ['city_id' => '97', 'city_name' => 'Mithi', 'city_state' => 'Sindh'],
    ['city_id' => '98', 'city_name' => 'Bannu', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '99', 'city_name' => 'Timargara', 'city_state' => 'Khyber Pakhtunkhwa'],
    ['city_id' => '100', 'city_name' => 'Parachinar', 'city_state' => 'Khyber Pakhtunkhwa'],
];